### ISSUE TITLE
When set, `dc_spatial` document metadata should be displayed

### ISSUE THREAD

**Issue by benel** [Hypertopic/HyperGlosae#48]
In the @Hypertopic/arts-plastiques project, pictures are labelled with the country of the young artist. 
This country could be set with the `dc_spatial` attribute. 

For now, this attribute is not displayed in references and main document titles.

### Deliverables status

- [ ] Scenarios (Gherkin)
- [ ] Acceptance tests (Capybara)
- [ ]  Implementation strategy
- [ ] Implementation

**Comment by StachoB** [comment]
This fix ticket corresponds to changing the way the title of the images are displayed (add the attribute dc_spacial to the text title). With the react dev tool we can identify that this title is in the metadat file, so it is the one we are going to work on.There should not be algorithm difficulties and we won't need to get other data since the information we are adding is already in data loaded on the page.
